# Generated by Django 4.2.13 on 2024-07-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_spoons',
            field=models.PositiveIntegerField(blank=True, default=12),
        ),
    ]
